# Generated by Django 2.2.11 on 2020-03-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match', models.CharField(db_column='Match', max_length=100)),
                ('Sports', models.CharField(db_column='Sports', max_length=100)),
                ('Point', models.IntegerField(db_column='Point')),
                ('Wonby', models.CharField(db_column='Wonby', max_length=10)),
                ('Lossby', models.CharField(db_column='Lossby', max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'teamsscore',
            },
        ),
    ]
